### Assignment 11 - Numpy
This assignment is based on the code provided in the following youtube video: https://www.youtube.com/watch?v=GB9ByFAIAH4

Nympy is fastter than regular list because of fixed types

### numpy array vs list:
a list in python stores a lot more information like Size , Refernece Cout, Object type and Object Value. This is fore every entry in the file.

Because numpy uses fixed types the extra datafiles are not required and therefore the array takes less space in ram.

### Memory
A python list only contains a pointer to where in the memory the data is stored. Numpy uses contiguous memory which greatly decrease load times(Effective Cache Utilization) from an array and utilises the SIMD vector Processing in the CPU.


### multiplying with numpy

In [158]:
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])
print("Multiplying",a,"and",b,a*b)

Multiplying [1 3 5] and [1 2 3] [ 1  6 15]


### Application of Numpy
* Mathlab replacement
* Backend
* image manipulation
* Machine Learning

In [159]:
import numpy as np
a = np.array([1,2,3],dtype='int32')
print(a)


[1 2 3]


### a list within a list

In [160]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### getting dimensions

In [161]:
print(a.ndim,b.ndim)


1 2


### Get Shape

In [162]:
print(a.shape,b.shape)

(3,) (2, 3)


# Get type

In [163]:
print(a.dtype,b.dtype)



int32 float64


### Get item size

In [164]:
print(a.itemsize,b.itemsize)

4 8


### Get total size

In [165]:
print(a.size*a.itemsize)
# or
print(a.nbytes)


12
12


## Accessing/Changing Specific elements, row colums, etc
* timestamp 16:16

In [166]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a,a.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] (2, 7)


### Get a specific element [r,c]

In [167]:
print(a[1,5])
# accessing same position only with negative positions
print(a[1,-2])

13
13


### get a row

In [168]:
print(a[0,:])

[1 2 3 4 5 6 7]


### get Column

In [169]:
print(a[:,2])


[ 3 10]


### Get every other item between 1 and 5 in row 0

In [170]:
#      row start stop step
print(a[0,1:6:2])

[2 4 6]


### Change value

In [171]:
a[1,5]=20
print(a)

# replace multiple numbers at the same time
a[:,2] =5
print(a)

# replace multiple numbers to a specific pattern
a[:,2] =[1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3d example

In [172]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Get specific element

In [173]:
print(b[0][1][1])
print(b[0,1,1])


4
4


### replace

In [174]:
print(b[:,1:])

#b[:,1:]=[[9,9],[8,8]]
print("\n",b[:,1:])

[[[3 4]]

 [[7 8]]]

 [[[3 4]]

 [[7 8]]]


### initializing Different Types of Arrays
* timestamp 23:00

In [175]:
# one dimension
print("one dimension",np.zeros(5))
# two dimention
print("Two dimension",np.zeros([2,3]))
print("3 dim.",np.zeros([2,3,3]))
print("4 dim",np.zeros([2,3,3,2]))



one dimension [0. 0. 0. 0. 0.]
Two dimension [[0. 0. 0.]
 [0. 0. 0.]]
3 dim. [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
4 dim [[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


### all ones


In [176]:
print(np.ones((4,2,2),dtype='int32'))

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


### specific number

In [177]:
#    shape, value
print(np.full((2,2),99))

[[99 99]
 [99 99]]


### any other number(Full)

In [178]:
# takes an array and make a new array with specified value but the same shape as imported array
print(np.full_like(a,4))
print(np.full(a.shape,4))

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


### Array of random decimal numbers

In [179]:
print(np.random.rand(4,2))
print(np.random.random_sample(a.shape))

[[0.97818896 0.64655033]
 [0.1934268  0.8903882 ]
 [0.04500907 0.43827969]
 [0.00310987 0.95500012]]
[[0.02061044 0.38101265 0.65029921 0.15557789 0.48450317 0.11337749
  0.57241104]
 [0.27184232 0.56026384 0.62921173 0.5239485  0.21871637 0.35799038
  0.1705976 ]]


### number integer

In [180]:
print(np.random.randint(-3,7,size=(3,3)))

[[ 0  3  4]
 [ 1  1  0]
 [-3 -2  6]]


### identity matrix

In [181]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Repeat an array

In [182]:
array = np.array([[1,2,3,4]])
rp = np.repeat(array,3,axis=0)
print(rp)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


### task at 31:40

In [183]:
output =np.full((5,5),1)
zero = np.zeros((3,3))
zero[1,1]=9
output[1:4,1:4]=zero
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Copy

In [184]:
# Direct copy
a = np.array([1,2,3])
b = a
print("a",a,"b",b)
print("after change")
b[0]=100
print("a",a,"b",b)

# Deap copy
a = np.array([1,2,3])
#b = np.copy(a)
b = a.copy()
print("a",a,"b",b)
print("after change")
b[0]=100
print("a",a,"b",b)


a [1 2 3] b [1 2 3]
after change
a [100   2   3] b [100   2   3]
a [1 2 3] b [1 2 3]
after change
a [1 2 3] b [100   2   3]


## Mathematics
* timestamp 35:45
### element wise operation

In [185]:
a = np.array([1,2,3,4])
print(a)
print("a+2",a+2)
print("a-2",a-2)
print("a*2",a*2)
print("a/2",a/2)

b= np.array([1,0,1,0])
print("a+b",a+b)
print("sin(a)",np.sin(a))
print("cos(a)",np.cos(a))
print("tan(a)",np.tan(a))

[1 2 3 4]
a+2 [3 4 5 6]
a-2 [-1  0  1  2]
a*2 [2 4 6 8]
a/2 [0.5 1.  1.5 2. ]
a+b [2 2 4 4]
sin(a) [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos(a) [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan(a) [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


## Linear Algebra
* timestamp 38:18

In [186]:
a = np.full((2,3),1)
print(a)
b = np.full((3,2),2)
print(b)
print("a*b",np.matmul(a,b))
c = np.identity(3)
print("Determinate of c\n",c,"\nis:\n",np.linalg.det(c))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]
a*b [[6 6]
 [6 6]]
Determinate of c
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
is:
 1.0


### Statistics
* Timestamp 42:19

In [187]:
stats = np.array([[1,2,3],[4,5,6]])
print("min",np.min(stats))
print("max",np.max(stats))
print("Row with max value",np.max(stats,axis=0))
print("column with max value",np.max(stats,axis=1))

min 1
max 6
Row with max value [4 5 6]
column with max value [3 6]


### Reorganizing Arrays
* timestamp 43:59

In [188]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("the array:\n",before,"\nHas an",before.shape,"shape")
# note needs to have the same amout og values
after = before.reshape((8,1))
print("the array:\n",after,"\nHas an",after.shape,"shape")

the array:
 [[1 2 3 4]
 [5 6 7 8]] 
Has an (2, 4) shape
the array:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 
Has an (8, 1) shape


### Vertical stacking vectores

In [189]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
print(np.vstack([v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]


### Horizontal stacking vectors

In [190]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack((h1,h2)))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## Miscellaneous
* timestamp 47:40
### Load Data from file

In [191]:
# note new line vil be delimiter for one row
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   5   6   7   0  11  12  10]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced indexing

In [192]:
# where in file is the value grater than 50
print("where in file is the value grater than 50\n",filedata>50)
print("Returning data that is greater than 50",filedata[filedata > 50])

where in file is the value grater than 50
 [[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
Returning data that is greater than 50 [196  75 766  75  55 999  78  76  88]


### Index With a list in NumPY

In [193]:
a = np.array([1,2,3,4,5,6,7,8,9])
# return values in position 1 2 and 8
print(a[[1,2,8]])

print("Display columns with the numbers larger than 50\n",np.any(filedata>50,axis=0))
print("Display columns with ALL the numbers larger than 50\n",np.all(filedata>50,axis=0))

[2 3 9]
Display columns with the numbers larger than 50
 [False False False False  True  True False  True  True False False False
 False False False False  True  True]
Display columns with ALL the numbers larger than 50
 [False False False False  True False False False False False False False
 False False False False False False]


### task2 at 56:00

In [194]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,28,30]])
print(a,"\n")
print((a[[2,3]])[:,:2],"\n")
print(a[2:4,0:2],"\n")
print(a[[0,1,2,3],[1,2,3,4]],"\n")
print(a[[0,-2,-1],3:],"\n")




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 28 30]] 

[[11 12]
 [16 17]] 

[[11 12]
 [16 17]] 

[ 2  8 14 20] 

[[ 4  5]
 [24 25]
 [28 30]] 

